using System.Text;
using System.Text.RegularExpressions;

namespace UORegionEditor;

public class ScpImportResult
{
    public List<RegionDef> Regions { get; } = new();
    public List<string> OtherSections { get; } = new();  // verbatim non-region blocks ([COMMENT ...], VERSION preamble, ...)
}

// Export/import of Sphere AREADEF/ROOMDEF scripts:
//   [AREADEF A_TOWN_SQUARE]
//   EVENTS=r_default,...,R_TOWN_GUARDED
//   NAME=Town Square
//   FLAGS=region_flag_nobuilding|...
//   P=1387,1620,30,0
//   RECT=1376,1604,1401,1644,0        <- right/bottom edges EXCLUSIVE (inclusive tile + 1)
//
// Parsing mirrors Sphere's own leniencies (verified against Source-X):
//  - section keyword matched by PREFIX (the stock file's [AREADEFF ...] typos are live regions)
//  - numbers parsed atoi-style, leading digits win ("2579.0" -> 2579)
//  - repeated EVENTS= lines ACCUMULATE
public static class SphereScp
{
    static readonly Regex SeparatorComment = new(@"^\s*//\s*[-/=]{5,}\s*$");
    // Banner lines this tool wrote on a previous export, stripped on import so they never
    // stack up. The "Script <field>:" shape is the header older versions wrote.
    static readonly Regex GeneratedComment = new(
        @"^\s*//\s*Script\s+\w+\s*:|UORegionEditor",
        RegexOptions.IgnoreCase);

    public static string SanitizeDefName(string s, int fallbackIndex)
    {
        s = (s ?? "").Trim();
        var cleaned = new string(s.Select(ch => char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_').ToArray());
        while (cleaned.Contains("__")) cleaned = cleaned.Replace("__", "_");
        cleaned = cleaned.Trim('_');
        return cleaned.Length == 0 ? $"A_UNNAMED_{fallbackIndex}" : cleaned;
    }

    public static string Export(Project p, IEnumerable<RegionDef> regions)
    {
        var sb = new StringBuilder();
        // every generated line carries "UORegionEditor" so GeneratedComment can strip the
        // whole banner again on re-import instead of stacking a new one each round
        sb.AppendLine("// ---------------------------------------");
        sb.AppendLine($"// Generated by UORegionEditor - {DateTime.Now:yyyy-MM-dd}");
        sb.AppendLine("// ---------------------------------------");
        sb.AppendLine();
        int add = p.SphereExclusiveEdge ? 1 : 0;
        int idx = 0;
        foreach (var r in regions)
        {
            idx++;
            if (r.Rects.Count == 0) continue;   // a RECT-less areadef is broken; skip empties
            foreach (var c in r.Comments) sb.AppendLine(c);
            string kind = (r.Kind ?? "AREADEF").StartsWith("ROOMDEF", StringComparison.OrdinalIgnoreCase) ? "ROOMDEF" : "AREADEF";
            sb.AppendLine($"[{kind} {SanitizeDefName(r.DefName, idx).ToUpperInvariant()}]");
            if (!string.IsNullOrWhiteSpace(r.Events)) sb.AppendLine($"EVENTS={r.Events}");
            sb.AppendLine($"NAME={r.Name}");
            if (!string.IsNullOrWhiteSpace(r.Group)) sb.AppendLine($"GROUP={r.Group}");
            if (!string.IsNullOrWhiteSpace(r.Flags)) sb.AppendLine($"FLAGS={r.Flags}");
            var (px, py) = r.EffectiveP();
            sb.AppendLine($"P={px},{py},{r.PZ},{r.MapPlane}");
            sb.AppendLine($"// {DateTime.Now:yyyy-MM-dd} UORegionEditor: {r.Rects.Count} boxes{(add == 1 ? " (RECT right/bottom edges exclusive -> +1)" : "")}");
            foreach (var rc in r.Rects)
                sb.AppendLine($"RECT={rc.X1},{rc.Y1},{rc.X2 + add},{rc.Y2 + add},{r.MapPlane}");
            foreach (var x in r.Extra) sb.AppendLine(x);
            sb.AppendLine();
            sb.AppendLine("// ---------------------------------------");
            sb.AppendLine();
        }
        foreach (var block in p.ExtraSections)
        {
            sb.AppendLine(block.TrimEnd());
            sb.AppendLine();
        }
        sb.AppendLine("[EOF]");
        return sb.ToString();
    }

    // compact form for automated exports (the server writes this next to regions.json):
    // no banner, no comments - just the functional lines, ready to include from sphere scripts
    public static string ExportCompact(IEnumerable<RegionDef> regions, bool exclusiveEdge = true)
    {
        var sb = new StringBuilder();
        int add = exclusiveEdge ? 1 : 0;
        int idx = 0;
        foreach (var r in regions)
        {
            idx++;
            if (r.Rects.Count == 0) continue;
            string kind = (r.Kind ?? "AREADEF").StartsWith("ROOMDEF", StringComparison.OrdinalIgnoreCase) ? "ROOMDEF" : "AREADEF";
            sb.AppendLine($"[{kind} {SanitizeDefName(r.DefName, idx).ToUpperInvariant()}]");
            if (!string.IsNullOrWhiteSpace(r.Events)) sb.AppendLine($"EVENTS={r.Events}");
            sb.AppendLine($"NAME={r.Name}");
            if (!string.IsNullOrWhiteSpace(r.Group)) sb.AppendLine($"GROUP={r.Group}");
            if (!string.IsNullOrWhiteSpace(r.Flags)) sb.AppendLine($"FLAGS={r.Flags}");
            var (px, py) = r.EffectiveP();
            sb.AppendLine($"P={px},{py},{r.PZ},{r.MapPlane}");
            foreach (var rc in r.Rects)
                sb.AppendLine($"RECT={rc.X1},{rc.Y1},{rc.X2 + add},{rc.Y2 + add},{r.MapPlane}");
            foreach (var x in r.Extra) sb.AppendLine(x);
            sb.AppendLine();
        }
        sb.AppendLine("[EOF]");
        return sb.ToString();
    }

    public static ScpImportResult Import(string text, bool exclusiveEdge, int colorSeed = 0)
    {
        var result = new ScpImportResult();
        RegionDef cur = null;
        StringBuilder curOther = null;               // verbatim collector for a non-region section
        var pendingComments = new List<string>();    // comments waiting to attach to the next section
        var preamble = new List<string>();           // non-comment lines before the first section (VERSION=X ...)
        bool blankAfterBody = false;                 // a blank line ended the current region body
        int colorIdx = colorSeed;

        void FlushOther()
        {
            if (curOther != null && curOther.Length > 0)
                result.OtherSections.Add(curOther.ToString().TrimEnd());
            curOther = null;
        }

        text = text.TrimStart('﻿');
        foreach (var raw in text.Replace("\r\n", "\n").Split('\n'))
        {
            var line = raw.TrimEnd();
            var t = line.Trim();

            if (t.StartsWith("["))
            {
                int close = t.IndexOf(']');
                var inner = close > 0 ? t.Substring(1, close - 1).Trim() : "";
                var parts = inner.Split(new[] { ' ', '\t' }, StringSplitOptions.RemoveEmptyEntries);
                bool isRegion = parts.Length >= 2 &&
                    (parts[0].StartsWith("AREADEF", StringComparison.OrdinalIgnoreCase) ||
                     parts[0].StartsWith("ROOMDEF", StringComparison.OrdinalIgnoreCase));
                bool isEof = parts.Length >= 1 && parts[0].Equals("EOF", StringComparison.OrdinalIgnoreCase);

                FlushOther();
                cur = null;
                blankAfterBody = false;

                if (isRegion)
                {
                    cur = new RegionDef
                    {
                        Kind = parts[0].StartsWith("ROOMDEF", StringComparison.OrdinalIgnoreCase) ? "ROOMDEF" : "AREADEF",
                        DefName = parts[1],
                        Name = parts[1],
                        Comments = new List<string>(pendingComments),
                    };
                    cur.Color = Palette.Next(colorIdx++);
                    result.Regions.Add(cur);
                    pendingComments.Clear();
                }
                else if (!isEof)
                {
                    // unknown section ([COMMENT ...], [DEFNAME ...], ...) - keep it verbatim
                    curOther = new StringBuilder();
                    foreach (var pc in pendingComments) curOther.AppendLine(pc);
                    pendingComments.Clear();
                    curOther.AppendLine(line);
                }
                else
                {
                    pendingComments.Clear();
                }
                continue;
            }

            if (curOther != null)
            {
                curOther.AppendLine(line);
                continue;
            }

            if (t.Length == 0)
            {
                if (cur != null) blankAfterBody = true;
                continue;
            }

            if (t.StartsWith("//"))
            {
                if (SeparatorComment.IsMatch(t) || GeneratedComment.IsMatch(t)) continue;
                if (cur == null || blankAfterBody) pendingComments.Add(line);
                else cur.Extra.Add(line);
                continue;
            }

            if (cur == null)
            {
                preamble.Add(line);                  // e.g. VERSION=X
                continue;
            }

            if (blankAfterBody)
            {
                // the region body continues after a blank line: the buffered comments belong to it after all
                cur.Extra.AddRange(pendingComments);
                pendingComments.Clear();
                blankAfterBody = false;
            }

            int eq = t.IndexOf('=');
            if (eq < 0) { cur.Extra.Add(line); continue; }
            var key = t.Substring(0, eq).Trim().ToUpperInvariant();
            var val = t.Substring(eq + 1).Trim();

            switch (key)
            {
                case "NAME": cur.Name = val; break;
                case "EVENTS":
                    // Sphere accumulates repeated EVENTS= lines
                    cur.Events = string.IsNullOrWhiteSpace(cur.Events) ? val : cur.Events + "," + val;
                    break;
                case "FLAGS": cur.Flags = val; break;
                case "GROUP": cur.Group = val; break;
                case "P":
                {
                    var a = SplitInts(val);
                    if (a.Count >= 2)
                    {
                        cur.PX = a[0]; cur.PY = a[1];
                        cur.PZ = a.Count >= 3 ? a[2] : 0;
                        if (a.Count >= 4) cur.MapPlane = a[3];
                    }
                    break;
                }
                case "RECT":
                {
                    var a = SplitInts(val);
                    if (a.Count >= 4)
                    {
                        int sub = exclusiveEdge ? 1 : 0;
                        var rr = new RegionRect(a[0], a[1], a[2], a[3]); // normalizes swapped corners
                        rr.X2 = Math.Max(rr.X1, rr.X2 - sub);
                        rr.Y2 = Math.Max(rr.Y1, rr.Y2 - sub);
                        cur.Rects.Add(rr);
                        if (a.Count >= 5) cur.MapPlane = a[4];
                    }
                    else
                    {
                        cur.Extra.Add("// UNPARSED: " + line.Trim());
                    }
                    break;
                }
                default:
                    cur.Extra.Add(line);
                    break;
            }
        }
        FlushOther();
        if (preamble.Count > 0 && preamble.Any(l => !l.StartsWith("[")))
            result.OtherSections.Insert(0, string.Join(Environment.NewLine, preamble));
        return result;
    }

    // atoi-style: leading digits win ("2579.0" -> 2579), stop at the first token with no digits.
    static List<int> SplitInts(string s)
    {
        var list = new List<int>();
        foreach (var part in s.Split(','))
        {
            var q = part.Trim();
            int j = 0;
            if (j < q.Length && (q[j] == '-' || q[j] == '+')) j++;
            int start = j;
            while (j < q.Length && char.IsDigit(q[j])) j++;
            if (j == start) break;
            if (int.TryParse(q.Substring(0, j), out int v)) list.Add(v);
            else break;
        }
        return list;
    }
}
